name: lint

on: pull_request

env:
  GO111MODULE: on

permissions:
  contents: read

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.x
          cache-dependency-path: "**/go.sum"
      - run: make lint
